# Generated by Django 5.2.1 on 2025-05-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Institutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("accepted_zones", models.CharField(max_length=250)),
                ("about", models.TextField(null=True)),
            ],
            options={
                "db_table": "institutions",
            },
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "languages",
            },
        ),
        migrations.CreateModel(
            name="Prerequisites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "prerequisites",
            },
        ),
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                (
                    "level_of_difficulty",
                    models.CharField(
                        choices=[
                            ("0", "easy"),
                            ("1", "je ne sais pas 1"),
                            ("2", "je ne sais pas 2"),
                            ("3", "je ne sais pas 3"),
                            ("4", "je ne sais pas 4"),
                        ],
                        default="0",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("duration_of_validity", models.CharField(null=True)),
                ("image", models.ImageField(upload_to="certification")),
                ("link", models.URLField()),
                ("discounts", models.CharField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.category",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.institutions",
                    ),
                ),
                (
                    "languages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.languages",
                    ),
                ),
                (
                    "prerequisites",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.prerequisites",
                    ),
                ),
            ],
            options={
                "db_table": "certifications",
            },
        ),
    ]
