# Generated by Django 5.2.1 on 2025-06-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'db_table': 'topic',
            },
        ),
        migrations.AddField(
            model_name='certifications',
            name='topic',
            field=models.ManyToManyField(to='certification.topic'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('level_of_difficulty', models.CharField(choices=[('0', 'easy'), ('1', 'medium'), ('2', 'hard'), ('3', 'very hard'), ('4', 'impossible')], default='0', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('duration_of_validity', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='certification')),
                ('exam_site', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('discounts', models.CharField(max_length=50, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('category', models.ManyToManyField(to='certification.category')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certification.institutions')),
                ('languages', models.ManyToManyField(to='certification.languages')),
                ('prerequisites', models.ManyToManyField(to='certification.prerequisites')),
                ('topic', models.ManyToManyField(to='certification.topic')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'unique_together': {('name', 'institution')},
            },
        ),
    ]
