# Generated by Django 5.2.1 on 2025-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_topic_certifications_topic_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='level_of_difficulty',
            field=models.CharField(choices=[('0', 'easy'), ('1', 'medium'), ('2', 'hard'), ('3', 'very-hard'), ('4', 'impossible')], default='0', max_length=20),
        ),
    ]
