# Generated by Django 5.2.1 on 2025-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_alter_certifications_level_of_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='level_of_difficulty',
            field=models.CharField(choices=[('0', 'easy'), ('1', 'medium'), ('2', 'hard'), ('3', 'extreme'), ('4', 'impossible')], default='0', max_length=20),
        ),
    ]
