# Generated by Django 5.2.1 on 2025-06-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_alter_certifications_level_of_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='certification.certifications'),
        ),
    ]
