# Generated by Django 5.2.1 on 2025-07-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_alter_category_name_alter_certifications_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='institutions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certification'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certification'),
        ),
    ]
