# Generated by Django 5.2.1 on 2025-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_remove_course_prerequisites_institutions_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='certification'),
        ),
    ]
